### ISSUE TITLE
Notifications of Design System version changes

### ISSUE THREAD

**Issue by karlaturcios** [18F/identity-style-guide#103]
Consider a way to communicate version changes to the Design System. This helps apps that may have a dependency to the design system in the package.json like this example:

` "identity-style-guide": "^2.1.3"`

**Comment by karlaturcios** [comment]
Automating notification of updates to these other components would be great:

- footer/header updates

- meta tags

- JS files

- Vendor prefix settings

**Comment by porta-antiporta** [comment]
migrated LG-2640
