### ISSUE TITLE
Login.gov required form fields style

### ISSUE THREAD

**Issue by karlaturcios** [18F/identity-style-guide#104]
Please consider a required form fields style for the Login.gov design system. Partner forms have more optional fields than required fields, so a distinct style for required fields will assist the user in spotting the needed information both in filling out the form and identifying validation errors.

**Comment by karlaturcios** [comment]
For example, taken from USWDS: 
`    color: #981b1e;
    content: ' (*required)';`

**Comment by porta-antiporta** [comment]
migrated LG-2641
