### ISSUE TITLE
Create a style for code

### ISSUE THREAD

**Issue by karlaturcios** [18F/identity-style-guide#107]
Code samples is part of the content for Partners. Could we extend code formatting styles beyond markdown for styling code in Dashboard?

**Comment by donjo** [comment]
Can you give an example of where/how this might play out on the dashboard? Is this just a matter of configuring syntax highlighters for code we showcase on the dashboard site?

**Comment by karlaturcios** [comment]
Several instances occur on the Create New App form on the Partner dashboard site. If it's a configuration setup, what are the components involved?

**Comment by porta-antiporta** [comment]
migrated LG-2644
