### ISSUE TITLE
Add release notes to login design system

### ISSUE THREAD

**Issue by nickttng** [18F/identity-style-guide#120]
**Proposal:** Consider writing and adding release notes to `design.login.gov` site (Similar to [USWDS' release notes](https://designsystem.digital.gov/about/releases/)) 

**Stories:** 
- As a designer, I want to inform our login team members, esp. developers, of new features (and fixes), to show them that the login design team is listening to their feedback and that we are actively working to improve the login design system
- As a login team member, I want to be kept in the loop with release notes. As the design system evolves over time, having a historical log of these changes, improvements, and fixes helps tell stories behind the system

**Definition of Done:**
- [ ] Discuss this proposal with login designers, developers and product to gauge interest
- [ ] If 👍, proceed to create initial draft of release notes and format
- [ ] Establish a review process from drafting to publishing on `design.login.gov` site
- [ ] Create a _Release Notes_ page on `design.login.gov` site (Consider a subnav under [_Usage_](https://design.login.gov/usage/) section)

**Comment by porta-antiporta** [comment]
migrated LG-2646
