### ISSUE TITLE
Fix 404 error - Email template page

### ISSUE THREAD

**Issue by nickttng** [18F/identity-style-guide#122]
Currently, the [email template page on design.login.gov](https://design.login.gov/templates/email/) is 404-ing, which leads to Federalist default 404 message

## Email template page
![design login gov_templates_email_](https://user-images.githubusercontent.com/6327082/70928932-9bd48200-1ff7-11ea-9ebe-55debbec4bb5.png)

## Federalist 404 error page
![design login gov_examples_email-template html](https://user-images.githubusercontent.com/6327082/70929021-c6263f80-1ff7-11ea-9282-36d25873c611.png)

**Comment by porta-antiporta** [comment]
migrated LG-2647
