### ISSUE TITLE
Design side navigation option

### ISSUE THREAD

**Issue by karlaturcios** [18F/identity-style-guide#126]
As content grows in scope and depth, several products have a need for a navigation option that will allow for deeper taxonomy and labels that may be longer than the average width current top navigation system is set up for. 
A side navigation option is needed that will support web applications as well. These tend to have a toolbar to support user actions and global navigation nodes horizontally across the top. A side navigation would complement that type of information architecture.

**Comment by porta-antiporta** [comment]
migrated LG-2649
