### ISSUE TITLE
Create a figcaption style

### ISSUE THREAD

**Issue by nickttng** [18F/identity-style-guide#132]
**Why:** As a user looking at screenshots, illustrations, etc., I want to better understand what I am looking at via captions (HT: Karla R.)

**Use case example:** Captions for screenshots in [How to create an account](https://login.gov/help/creating-an-account/how-to-create-an-account/)

**Notes:**
- Use [USWDS Typesetting](https://designsystem.digital.gov/design-tokens/typesetting/overview/) to inform how we build it
- Research [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption) for `<figcaption>`, including `<figure>`

**AC:**
- Is accessible via contrast checker
- Is browser compatible for majority of our userbase
- Is added and documented on [login.gov design system - typography](https://design.login.gov/typography/) for wider use

**Update:** LG-2591 ticket created

**Comment by porta-antiporta** [comment]
tracking in JIRA
