### ISSUE TITLE
Add Hound CI to catch css syntax errors

### ISSUE THREAD

**Issue by gemfarmer** [18F/identity-style-guide#16]
As annoying as hound is, I think it is a really effective way of ensuring that our css code remains clean. A good example of this implementation is the 18F site:

- [`.hound.yml`](https://github.com/18F/18f.gsa.gov/blob/master/.hound.yml)
- [`circle.yml`](https://github.com/18F/18f.gsa.gov/blob/master/circle.yml)
- [`.scss-lint.yml`](https://github.com/18F/18f.gsa.gov/blob/master/.scss-lint.yml)

The lint file should probably be updated from the 18F/frontend repo: 

https://github.com/18F/frontend/blob/master/.scss-lint.yml

**Comment by adunkman** [comment]
Made obsolete by https://github.com/18F/identity-style-guide/pull/19, which runs linting in CI.
