### ISSUE TITLE
Add code styles documentation page.

### ISSUE THREAD

**Issue by adunkman** [18F/identity-style-guide#31]
As implemented in #30, code styles should be covered in the documentation, as login.gov will be using code styles as well downstream.

**Comment by el-mapache** [comment]
For clarification, should this be added to the `components` section of the style guide?

**Comment by adunkman** [comment]
I think so — but open to other ideas if you think it belongs elsewhere.

**Comment by adunkman** [comment]
Implemented in #46. Thanks @el-mapache!
