### ISSUE TITLE
Add usage instructions to Buttons page.

### ISSUE THREAD

**Issue by adunkman** [18F/identity-style-guide#37]
The [Buttons page](https://federalist-proxy.app.cloud.gov/site/18f/identity-style-guide/components/buttons/) currently has some placeholder text, which wasn’t originally written because I wasn’t aware of how the buttons should be used: 

> Use these button styles unless doing x and y, in which case, use other buttons.

> These buttons should be used when x-ing and y-ing.

I still don’t know how those buttons should be used, but we should have a reason why those styles exist, or delete them.

**Comment by porta-antiporta** [comment]
migrated to LG-2632
