### ISSUE TITLE
Stick sidebar navigation.

### ISSUE THREAD

**Issue by adunkman** [18F/identity-style-guide#38]
One of @rtwell’s pet-peeves about the US Web Design System styles was/is that the sidebar navigation on the left of pages isn’t accessible as you’re navigating through pages. 

We should be able to apply `.position-sticky` to that to get it to stick nicely… right? Right. I couldn’t get it working, even though it’s [covered in the U.S. Web Design System documentation](https://v2.designsystem.digital.gov/utilities/display/).

We’ll have to make sure that the bottom of longer menus are still accessible for longer menus on shorter height screens.

**Comment by porta-antiporta** [comment]
migrated to LG-2633
