### ISSUE TITLE
Implement file uploads.

### ISSUE THREAD

**Issue by adunkman** [18F/identity-style-guide#40]
As specified in [login-gov_styleguide_v1.9.3.sketch](https://drive.google.com/open?id=1v2vmmEXecBTx5UzZlA45k_KZC5oz1Yc3):

![Screenshot of specification in related Sketch document](https://user-images.githubusercontent.com/14930/51639372-beb4fe00-1f2e-11e9-880e-c1c0eb4e5729.png)

Unsure if we should do one or none of these: 

- Implement this fully as a JavaScript component + styles (similar to things like Accordions).
- Implement the styles for this (`.usa-input-file-large`), but leave the JavaScript implementation up to the application consuming this.
- Implement parts of the styles for this (`.usa-drop-target`, `.usa-file-preview`), but not glue them together, and leave the JavaScript implementation up to the application consuming this.

**Comment by porta-antiporta** [comment]
Migrated to LG-2634
