### ISSUE TITLE
Implement labels.

### ISSUE THREAD

**Issue by adunkman** [18F/identity-style-guide#42]
As specified in [login-gov_styleguide_v1.9.3.sketch](https://drive.google.com/open?id=1v2vmmEXecBTx5UzZlA45k_KZC5oz1Yc3):

![Screenshot of specification in Sketch file linked above](https://user-images.githubusercontent.com/14930/51640406-5d425e80-1f31-11e9-8fd8-bf756e57e2c1.png)

These should be an adaptation of [Labels in the U.S. Web Design System](https://v2.designsystem.digital.gov/components/labels/).

There should be some documentation added about the appropriate uses for these labels as well. What are those uses?

**Comment by donjo** [comment]
Currently put on hold since we don't actually use labels in our apps.
