### ISSUE TITLE
implement password strength meter.

### ISSUE THREAD

**Issue by adunkman** [18F/identity-style-guide#43]
As specified in [login-gov_styleguide_v1.9.3.sketch](https://drive.google.com/open?id=1v2vmmEXecBTx5UzZlA45k_KZC5oz1Yc3):

![Screenshot of related specification in Sketch](https://user-images.githubusercontent.com/14930/51640709-3fc1c480-1f32-11e9-8a02-2996a2a8a8bd.png)

Unclear of the best implementation for this — if we should include JavaScript for this, or just the styles.

**Comment by el-mapache** [comment]
I think there are a couple of  issues with including the JavaScript for this component:

* The current component has a hard dependency on the `zxcvbn` npm package which is fine but...
* the current component also has a hard dependency both on an I18n library supplied to the front-end via Rails, and on translation `yml` files in the provider app.

**Comment by donjo** [comment]
currently implemented
