### ISSUE TITLE
Implement tooltips.

### ISSUE THREAD

**Issue by adunkman** [18F/identity-style-guide#44]
As specified in [login-gov_styleguide_v1.9.3.sketch](https://drive.google.com/open?id=1v2vmmEXecBTx5UzZlA45k_KZC5oz1Yc3):

![Screenshot of specification in Sketch document](https://user-images.githubusercontent.com/14930/51640801-7d265200-1f32-11e9-9081-0440e11125e0.png)

The content in tooltips should remain accessible to those navigating by keyboards and to those on phones, as well as screen readers.

**Comment by el-mapache** [comment]
I don't actually see a tooltip anywhere on the IDP site, is this still worth implementing? Or have we moved away from tooltips as a pattern?

**Comment by adunkman** [comment]
Implemented in #48. Thanks @el-mapache!
