### ISSUE TITLE
Implement page partial templates.

### ISSUE THREAD

**Issue by adunkman** [18F/identity-style-guide#45]
The [Templates pages](https://federalist-proxy.app.cloud.gov/site/18f/identity-style-guide/templates/account-management/) in the documentation scaffolding seem to be relating to [Form Templates in the U.S. Web Design System](https://v2.designsystem.digital.gov/components/form-templates/), and will need discovery of what they are, and implementation in the style guide.

**Comment by porta-antiporta** [comment]
migrated to LG-2635
