### ISSUE TITLE
Consider / decide on icon set for standardization

### ISSUE THREAD

**Issue by nickttng** [18F/identity-style-guide#63]
The USWDS [recommends using Font Awesome (FA)](https://v2.designsystem.digital.gov/components/icons/).

**Current Issue:**
Meanwhile, Login does not have a standardized, default set option to pull from for the Login site/platform. Also, helpful for Login people to pull from for their slide decks.

**This task is competed when:**
- [ ] When Login Design and stakeholders have discussed on the pros and cons of having an icon set
   - [ ] If merited, then which icon set? Font Awesome? If not FA, then which set?
      - [ ] When decided, we'll include instructions to the style guide:
         - On implementation
         - On accessibility
         - On usability 
   - [ ] If _not_ merited, then how do we ensure that we have a consistent system of icons?

**Comment by nickttng** [comment]
Update: 18F Design is exploring icon sets to use. When decided, this will help login design team makes a choice.

**Comment by karlaturcios** [comment]
Please consider the following icon needs for Partner dashboard when selecting an icon set:
icons for navigation [My apps, Admin, Groups, Emails, Reporting, Home, Make new..., Login, Logout, Apps]
icons for status [States for Apps: Active, In Production; Environments status: deploy-success, deploy-error, disabled]
icons for users status [Signed in, Never Signed In, Admin]
Icons for actions [edit, delete, back]

**Comment by karlaturcios** [comment]
A current feature in progress will need an icon. Could we reopen this discussion?

**Comment by nickttng** [comment]
@karlaturcios Yes — Is this something that could be created with a separate issue / story, or should it be shared in the same issue in this message thread?

**Comment by karlaturcios** [comment]
@nickttng Probably the same issue. We are looking for an arrow icon which is part of the wish list of standard icons.

**Comment by porta-antiporta** [comment]
Migrated to LG-2637
