### ISSUE TITLE
SASS Syntax in focus stylesheet

### ISSUE THREAD

**Issue by karlaturcios** [18F/identity-style-guide#90]
Possible bug in the syntax for function `roundable-focus-outline-box-shadows` in `_focus.scss`  
This code:
![Screen Shot 2019-06-24 at 12 19 41 PM](https://user-images.githubusercontent.com/1444176/60035410-c2ce7e80-967a-11e9-9637-bf544e449c17.png)
Generates this error:
![Screen Shot 2019-06-24 at 12 20 13 PM](https://user-images.githubusercontent.com/1444176/60035446-dbd72f80-967a-11e9-8e33-df5150ba73c4.png)
The function is likely expecting an argument declaration, like so:
`@function roundable-focus-outline-box-shadows () {
  @return
    0 0 0 $theme-focus-offset color('white'),
    0 0 0 $theme-focus-width + $theme-focus-offset color($theme-focus-color);
}`
The above syntax makes the error disappear.

**Comment by donjo** [comment]
@karlaturcios can you create a PR for this now that you have full github access?

**Comment by karlaturcios** [comment]
Closing issue, resolved with pull request #95
