### ISSUE TITLE
Include Autoprefixer for Ruby include in distributed package 

### ISSUE THREAD

**Issue by karlaturcios** [18F/identity-style-guide#96]
The autoprefixer for rails is missing in the design system.  The design systems vendor prefixer is currently is configure only in the gulp file, and it imports the configuration settings from https://github.com/uswds/uswds-gulp/blob/master/config/browsers.js. 
Ruby apps need something like this [autoprefixer ](https://github.com/ai/autoprefixer-rails) include in the distributed package and a long term plan to set the .browserslistrc in tangent with the USWDS settings.

**Comment by porta-antiporta** [comment]
Migrated LG-2639
