### ISSUE TITLE
Write selectors with hyphens instead of underscores

### ISSUE THREAD

**Issue by karlaturcios** [18F/identity-style-guide#97]
SCSS Linters raise issues on selectors like `` usa-checkbox__label`` using underscores and requests using hyphens instead. Several selectors in the design system use underscores which creates multiple linter issues.

**Comment by donjo** [comment]
Would we be able to adjust the linter rules to accept underscores? Since that's a pattern defined by the USWDS I'd like to follow their BEM naming scheme and not override it for login specific things if we can avoid that.

**Comment by karlaturcios** [comment]
SCSS Linter rules changed for the app
